### ISSUE TITLE
Align multiple text items by a delimiter (spacemacs/align-repeat)

### ISSUE THREAD

**Issue by geo7** [BrianHicks/spacemacs-rocks#14]
`SPC x a r`

`SPC x a <option>` are the `text-align` options.

Example : 

``` text
If, you, specify, a prefix, argument, (or,
you, must, enter, the, full, regular, expression,
The, function, also, then, prompts, for, which,
```

Select area of text (`vip` for this) then `SPC x a r` and at the mini buffer prompt `,` will give

``` text
If  , you      , specify , a prefix , argument , (or     ,
you , must     , enter   , the      , full     , regular , expression ,
The , function , also    , then     , prompts  , for     , which      ,

```

**Comment by BrianHicks** [comment]
FWIW: I just now used this to solve a problem even though I haven't scheduled it yet, so this is definitely coming up soon, and thanks for the contribution. :D

**Comment by geo7** [comment]
yea its nice :) I was using align-regexp before but this will do multiple, which is nice

**Comment by BrianHicks** [comment]
Got this scheduled for October 1. If you have any additions or corrections before then, please let me know or just open up a PR. :)
