### ISSUE TITLE
navigate through flymake errors

### ISSUE THREAD

**Issue by ryane** [BrianHicks/spacemacs-rocks#16]
@ryanesc on Twitter (http://ryaneschinger.com)

Use `SPC e n` and `SPC e p` to navigate to next and previous flymake errors in the current buffer.

**Comment by BrianHicks** [comment]
I've got this scheduled for Tuesday the 22nd. If you'd like to make any edits, let me know before (or after, really, then)

**Comment by ryane** [comment]
awesome
