### ISSUE TITLE
Kmacro tip doesn't work with `q` macros intuitively 

### ISSUE THREAD

**Issue by geo7** [BrianHicks/spacemacs-rocks#18]
If one creates a macro using `q<char>` (as in Vim) then edits using the tip explained here; 

https://github.com/BrianHicks/spacemacs-rocks/blob/master/content/posts/kmacro-edit-macro.md

It will then have to be called using the standard emacs method of `f4`. 

There's probably a way to copy it back into the register and use the edited macro from  `@<char>` , just thought that I would mention this caveat though

**Comment by BrianHicks** [comment]
noted, thanks
