### ISSUE TITLE
Turn a buffer into HTML content with htmlize

### ISSUE THREAD

**Issue by geo7** [BrianHicks/spacemacs-rocks#19]
I've not got a massive amount of use for this myself, but It's pretty neat all the same. Vim has similar functionality with `:TOhtml`. 

Basically in any buffer run : 

`M-x` then `htmlize-buffer`

This will export the content of the buffer to a html file, syntax highlighting and everything. 

Also @BrianHicks -> the blog appears to be displaying wonky on my browsers (firefox and chrome)

**Comment by BrianHicks** [comment]
Neat tip, thanks! Would you take some screenshots of the issue and attach
them to a new ticket please?

**Comment by BrianHicks** [comment]
This will be posted on Tuesday, thanks! Check the file I'm about to push and let me know if you have any changes.

As far as the "wonky" issue, were you accessing the site by HTTPS? That's fixed in #25

**Comment by geo7** [comment]
no worries - the site looks fine now btw sorry I didn't get back with more information :/
