### ISSUE TITLE
spacemacs startup screen key bindings

### ISSUE THREAD

**Issue by d12frosted** [BrianHicks/spacemacs-rocks#2]
In spacemacs startup screen there are few useful key bindings:
- `tab` (`widget-forward`) - jump to next widget
- `backtab` (`widget-backward`) - jump to previous widget
- `r` - jump to first widget under `Recent files`
- `m` - jump to first widget under `Bookmarks`
- `p` - jump to first widget under `Projects`

The last three are extremely helpful. So for example, if you want to open second file in `Recent files` list you click `r <tab> <return>`.

**Comment by srid** [comment]
Good to know about `r` - would be useful.

**Comment by d12frosted** [comment]
Cool. Sorry about the title - I saw another tip proposal with `Tip:` in title, thought it's what you want :smile: Wasn't clear from contributing guide.

**Comment by BrianHicks** [comment]
@d12frosted that's fine! I just thought I'd make them all the same. :)

**Comment by BrianHicks** [comment]
@d12frosted your tip is scheduled for 2015-09-10. If you've got any edits to the tip content before then, just let me know!
