### ISSUE TITLE
https site doesn't have styles

### ISSUE THREAD

**Issue by edpaget** [BrianHicks/spacemacs-rocks#25]
I really wanted to try to fix it, but I couldn't find where the css is included from. It looks like they're being loaded as over http instead of https, so Firefox and Chrome won't load them when you go to https://spacemacs.brianthicks.com/

**Comment by BrianHicks** [comment]
Fixed in https://github.com/BrianHicks/spacemacs-rocks/commit/699cb6adc6b96e049e70e6d9cd5b71b269889e54. Thanks, @edpaget!
