### ISSUE TITLE
List all function definitions inside a file (searchable by default)

### ISSUE THREAD

**Issue by 526avijitgupta** [BrianHicks/spacemacs-rocks#28]
**Avijit Gupta**: @526avijitgupta on GitHub
To list all the function definitions in the current buffer, use `SPC s l`.
Just start typing to start searching inside them!

**Comment by BrianHicks** [comment]
This has been published with #4 (http://spacemacs.brianthicks.com/2015/09/15/search-within-a-buffer/)

Thanks, though!
