### ISSUE TITLE
fix helm after loosing focus

### ISSUE THREAD

**Issue by d12frosted** [BrianHicks/spacemacs-rocks#3]
As described in https://github.com/syl20bnr/spacemacs/issues/2851 - `SPC w b` fixes it.

**Comment by srid** [comment]
Helm losing focus and thereby freezing (you cannot mouse-click your way back for some reason) always frustrated me as I did not know about `SPC w b`.

**Comment by BrianHicks** [comment]
how could I get helm in that state to demonstrate?

**Comment by louy2** [comment]
Open helm by whatever (such as `SPC f f`) and mouse click out of it.

**Comment by BrianHicks** [comment]
Thanks, I've got this scheduled for tomorrow!
