### ISSUE TITLE
C-o and C-i to move in jump history

### ISSUE THREAD

**Issue by BrianHicks** [BrianHicks/spacemacs-rocks#8]
> Use C-o and C-i to jump backward and forward between previous jump locations.
> Note: In Emacs, C-i and TAB are equivalent

Submitted by Bar... waiting for a linkable credit!

**Comment by bmag** [comment]
Sorry, didn't see your email until now. Linking to my GitHub profile is good (https://github.com/bmag)

**Comment by BrianHicks** [comment]
Sounds great, thanks!

**Comment by BrianHicks** [comment]
This is set to be published on October 13, thanks for the tip. The commit: https://github.com/BrianHicks/spacemacs-rocks/commit/5253e2f9e032d07203fadaf5aa370b41f65d6c99. If anything looks wrong yell at me or just open a PR. :)
